name: üî•Aplica√ß√£o
description: Issues relacionadas √†s aplica√ß√µes desenvolvidas no treinamento
title: "Aplica√ß√£o: [NOME_DA_APLICA√á√ÉO]"
labels: [üî•aplica√ß√£o]
body:
  - type: dropdown
    id: colors-check
    attributes:
      label: As cores da sua vers√£o da aplica√ß√£o s√£o diferentes das cores da aplica√ß√£o mostrada na aula?
      options:
        - Sim
        - N√£o
    validations:
      required: true
  - type: dropdown
    id: functionality-check
    attributes:
      label: A aplica√ß√£o cont√©m funcionalidades que n√£o foram mostradas nas aulas?
      options:
        - Sim
        - N√£o
    validations:
      required: true
  - type: dropdown
    id: language-features-check
    attributes:
      label: A aplica√ß√£o cont√©m features da linguagem que n√£o foram mostradas nas aulas?
      options:
        - Sim
        - N√£o
    validations:
      required: true
  - type: input
    id: repo-link
    attributes:
      label: Link do reposit√≥rio da aplica√ß√£o
      placeholder: Insira aqui o link do reposit√≥rio da sua aplica√ß√£o
    validations:
      required: true
  - type: textarea
    id: obstacles
    attributes:
      label: Maiores dificuldades durante a implementa√ß√£o
    validations:
      required: true
  - type: textarea
    id: easiness
    attributes:
      label: Menores dificuldades durante a implementa√ß√£o
    validations:
      required: true
